// <auto-generated />
using System;
using Kolos2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kolos2.Migrations
{
    [DbContext(typeof(KolosDbContext))]
    [Migration("20200612133431_full_database")]
    partial class full_database
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kolos2.Models.Klient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Klients");
                });

            modelBuilder.Entity("Kolos2.Models.Pracownik", b =>
                {
                    b.Property<int>("idPracownik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPracownik");

                    b.ToTable("Pracowniks");
                });

            modelBuilder.Entity("Kolos2.Models.WyrobCukierniczy", b =>
                {
                    b.Property<int>("IdWyrobuCukierniczego")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("CenaZaSzt")
                        .HasColumnType("real");

                    b.Property<string>("Typ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdWyrobuCukierniczego");

                    b.ToTable("WyrobCukierniczies");
                });

            modelBuilder.Entity("Kolos2.Models.Zamowienie", b =>
                {
                    b.Property<int>("IdZamowieni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataPrzyjecia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRealizacji")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdKlient")
                        .HasColumnType("int");

                    b.Property<int>("IdPracownik")
                        .HasColumnType("int");

                    b.Property<int?>("KlientId")
                        .HasColumnType("int");

                    b.Property<int?>("PracownikidPracownik")
                        .HasColumnType("int");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdZamowieni");

                    b.HasIndex("KlientId");

                    b.HasIndex("PracownikidPracownik");

                    b.ToTable("Zamowienies");
                });

            modelBuilder.Entity("Kolos2.Models.Zamowienie_WyrobCukierniczy", b =>
                {
                    b.Property<int>("IdWyrobCukierniczy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdZamowienia")
                        .HasColumnType("int");

                    b.Property<int>("Ilosc")
                        .HasColumnType("int");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WyrobCukierniczyIdWyrobuCukierniczego")
                        .HasColumnType("int");

                    b.Property<int?>("ZamowienieIdZamowieni")
                        .HasColumnType("int");

                    b.HasKey("IdWyrobCukierniczy");

                    b.HasIndex("WyrobCukierniczyIdWyrobuCukierniczego");

                    b.HasIndex("ZamowienieIdZamowieni");

                    b.ToTable("zamowienie_WyrobCukierniczies");
                });

            modelBuilder.Entity("Kolos2.Models.Zamowienie", b =>
                {
                    b.HasOne("Kolos2.Models.Klient", "Klient")
                        .WithMany("Zamowienies")
                        .HasForeignKey("KlientId");

                    b.HasOne("Kolos2.Models.Pracownik", "Pracownik")
                        .WithMany("Zamowienies")
                        .HasForeignKey("PracownikidPracownik");
                });

            modelBuilder.Entity("Kolos2.Models.Zamowienie_WyrobCukierniczy", b =>
                {
                    b.HasOne("Kolos2.Models.WyrobCukierniczy", "WyrobCukierniczy")
                        .WithMany()
                        .HasForeignKey("WyrobCukierniczyIdWyrobuCukierniczego");

                    b.HasOne("Kolos2.Models.Zamowienie", "Zamowienie")
                        .WithMany()
                        .HasForeignKey("ZamowienieIdZamowieni");
                });
#pragma warning restore 612, 618
        }
    }
}
